<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0gMG1Bc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0gMG1Bc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0gMG1Bc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0gMG1Bc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0gMG1Bc\App_KernelDevDebugContainer([
    'container.build_hash' => '0gMG1Bc',
    'container.build_id' => 'c8fa8b18',
    'container.build_time' => 1757500181,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0gMG1Bc');
