<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEfWlgaA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEfWlgaA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEfWlgaA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEfWlgaA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEfWlgaA\App_KernelDevDebugContainer([
    'container.build_hash' => 'EfWlgaA',
    'container.build_id' => 'c1792900',
    'container.build_time' => 1764063510,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEfWlgaA');
