<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU3u0mjA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU3u0mjA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU3u0mjA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU3u0mjA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU3u0mjA\App_KernelDevDebugContainer([
    'container.build_hash' => 'U3u0mjA',
    'container.build_id' => '31fa1cff',
    'container.build_time' => 1762251270,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU3u0mjA');
