<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_author' => [[], ['_controller' => 'App\\Controller\\AuthorController::index'], [], [['text', '/author']], [], [], []],
    'msg1_author' => [[], ['_controller' => 'App\\Controller\\AuthorController::msg1'], [], [['text', '/msg1']], [], [], []],
    'msg2_author' => [['var'], ['_controller' => 'App\\Controller\\AuthorController::msg2'], [], [['variable', '/', '[^/]++', 'var', true], ['text', '/msg2']], [], [], []],
    'msg3_author' => [['var'], ['_controller' => 'App\\Controller\\AuthorController::msg3'], [], [['variable', '/', '[^/]++', 'var', true], ['text', '/msg3']], [], [], []],
    'gotoindex_author' => [[], ['_controller' => 'App\\Controller\\AuthorController::goToIndex'], [], [['text', '/goToIndex']], [], [], []],
    'list_author' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::showDetails'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/showAuthor']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'App\Controller\AuthorController::index' => [[], ['_controller' => 'App\\Controller\\AuthorController::index'], [], [['text', '/author']], [], [], []],
    'App\Controller\AuthorController::msg1' => [[], ['_controller' => 'App\\Controller\\AuthorController::msg1'], [], [['text', '/msg1']], [], [], []],
    'App\Controller\AuthorController::msg2' => [['var'], ['_controller' => 'App\\Controller\\AuthorController::msg2'], [], [['variable', '/', '[^/]++', 'var', true], ['text', '/msg2']], [], [], []],
    'App\Controller\AuthorController::msg3' => [['var'], ['_controller' => 'App\\Controller\\AuthorController::msg3'], [], [['variable', '/', '[^/]++', 'var', true], ['text', '/msg3']], [], [], []],
    'App\Controller\AuthorController::goToIndex' => [[], ['_controller' => 'App\\Controller\\AuthorController::goToIndex'], [], [['text', '/goToIndex']], [], [], []],
    'App\Controller\AuthorController::listAuthors' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::showDetails'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/showAuthor']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
];
